service: syntesisTest

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256 # Overwrite the default memory size. Default is 1024
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  stage: prod
  region: us-west-2
  tags:
    APP_ENVIRONMENT: production
    PROJECT_NAME: syntesisTest
    PROJECT_FAMILY: Marketplace
    TEAM_OWNER: Marketplace
    CREATED_BY: Sergio Santos

plugins:
  - serverless-offline

functions:
  main:
    handler: handler.hello
    events:
      - http:
          path: /{path}
          method: post
      - http:
          path: /
          method: post
  teste:
    handler: Treino.teste
    events:
      - http:
          path: /treinoconcatena
          method: post
      - http:
          path: /treinosoma
          method: post    
     